delimiter ;
create table `kontoauszuege` (
  `id` int(11) not null,
  `bankkonto` varchar(255) not null,
  `buchungsdatum` date default null,
  `valuta` date default null,
  `betrag` decimal(15,2) default null,
  `waehrung` varchar(10) default null,
  `empfaengername1` varchar(255) default null,
  `empfaengername2` varchar(255) default null,
  `primanota` int(11) default null,
  `blz` varchar(15) default null,
  `kontonummer` varchar(30) default null,
  `verwendungszweck1` varchar(255) default null,
  `verwendungszweck2` varchar(255) default null,
  `verwendungszweck3` varchar(255) default null,
  `verwendungszweck4` varchar(255) default null,
  `verwendungszweck5` varchar(255) default null,
  `rechnungsnummer` varchar(400) default null,
  `zahlungsid` int(11) default null,
  `uniqueid` varchar(255) not null,
  `kontostand` decimal(15,2) default 0.00,
  primary key (`id`),
  unique key `uidx_kontoauszuege_uniqueid_n` (`uniqueid`),
  key `idx_ka_bd` (`buchungsdatum`),
  key `idx_ka_va` (`valuta`),
  key `idx_ka_e1` (`empfaengername1`),
  key `idx_ka_e2` (`empfaengername2`),
  key `idx_ka_blz` (`blz`),
  key `idx_ka_kno` (`kontonummer`),
  key `idx_ka_v1` (`verwendungszweck1`),
  key `idx_ka_v2` (`verwendungszweck2`),
  key `idx_ka_v3` (`verwendungszweck3`),
  key `idx_ka_v4` (`verwendungszweck4`),
  key `idx_ka_zi` (`zahlungsid`)
) engine=innodb default charset=utf8